version: 0.2
phases:
 install:
   commands:
     - 'node --version'
     - 'npm --version'
     - 'npm install'
 build:
   commands:
      - 'npm run build'
 post_build:
   commands:
      # - 'aws s3 sync dist s3://$S3_BUCKET_NAME/shepherding --delete'
      # - 'aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"'
